Sylius\Component\Product\Model\ProductVariantTranslation:
    exclusion_policy: ALL
    xml_root_name: variant
    properties:
        id:
            expose: true
            groups: [Default, Detailed, DetailedCart]
        locale:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        name:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
