# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

jms_serializer:
    metadata:
        directories:
            sylius-taxation:
                namespace_prefix: "Sylius\\Component\\Taxation"
                path: "@SyliusTaxationBundle/Resources/config/serializer"
