# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin_api_promotion:
    resource: |
        identifier: code
        alias: sylius.promotion
        section: admin_api
        grid: sylius_admin_api_promotion
        serialization_version: $version
        criteria:
            code: $code
    type: sylius.resource_api
