# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_admin_api_shipments:
    resource: |
        alias: sylius.shipment
        section: admin_api
        only: ['show', 'index']
        grid: sylius_admin_api_shipment
        serialization_version: $version
    type: sylius.resource_api
