# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

imports:
    - { resource: "config_test.yml" }

doctrine:
    orm:
        entity_managers:
            default:
                result_cache_driver:
                    type: memcached
                    host: localhost
                    port: 11211
                query_cache_driver:
                    type: memcached
                    host: localhost
                    port: 11211
                metadata_cache_driver:
                    type: memcached
                    host: localhost
                    port: 11211

twig:
    strict_variables: true

sylius_channel:
    debug: true

fos_rest:
    exception:
        debug: true
