bitbag_sylius_invoicing_plugin:
    resource: routing/admin.yml
    prefix: /admin

bitbag_sylius_invoicing_plugin_download_order_invoice:
    path: /invoice/{orderTokenValue}/download
    methods: [GET]
    defaults:
        _controller: bitbag_sylius_invoicing_plugin.controller.action.download_order_invoice
