imports:
    - { resource: services/form.yml }
    - { resource: services/controller.yml }
    - { resource: services/menu.yml }
    - { resource: services/resolver.yml }

services:
    bitbag_sylius_invoicing_plugin.file_generator.invoice_filename:
        class: BitBag\SyliusInvoicingPlugin\FileGenerator\InvoicePdfFilenameGenerator

    bitbag_sylius_invoicing_plugin.file_generator.invoice_file:
        class: BitBag\SyliusInvoicingPlugin\FileGenerator\InvoicePdfFileGenerator
        arguments:
            - "@knp_snappy.pdf"
            - "@templating"
            - "@bitbag_sylius_invoicing_plugin.resolver.company_data"
            - "@bitbag_sylius_invoicing_plugin.file_generator.invoice_filename"
            - "%invoices_root_dir%"

    bitbag_sylius_invoicing_plugin.validator.vat_number:
        class: BitBag\SyliusInvoicingPlugin\Validator\Constraints\VatNumberValidator
        tags:
            - { name: validator.constraint_validator, alias: bitbag_sylius_invoicing_plugin_vat_number_validator }

    bitbag_sylius_invoicing_plugin.email_manager.invoice:
        class: BitBag\SyliusInvoicingPlugin\EmailManager\InvoiceEmailManager
        arguments:
            - "@sylius.email_sender"
            - "@bitbag_sylius_invoicing_plugin.repository.invoice"
