Sylius\Component\Order\Model\Adjustment:
    exclusion_policy: ALL
    xml_root_name: order
    properties:
        id:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
        type:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        label:
            expose: true
            type: string
            groups: [Default, Detailed, DetailedCart]
        amount:
            expose: true
            type: integer
            groups: [Default, Detailed, DetailedCart]
