# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

jms_serializer:
    metadata:
        directories:
            sylius-promotion:
                namespace_prefix: "Sylius\\Component\\Promotion"
                path: "@SyliusPromotionBundle/Resources/config/serializer"
