sylius_grid:
    grids:
        sylius_admin_api_product:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.product.class%"
                    repository:
                        method: createListQueryBuilder
                        arguments: ["%locale%", $taxonId]
            sorting:
                code: asc
            fields:
                code:
                    type: string
                    sortable: ~
                name:
                    type: string
                    sortable: translation.name
            filters:
                search:
                    type: string
                    options:
                        fields: [code, translation.name]
                enabled:
                    type: boolean
